### ISSUE TITLE
filter specific requests

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/ApplicationInsights-server-dotnet#18]
Hello,

Is there a command to ignore specific requests just like new relic's ignore method?

**Comment by AlexBulankou** [comment]
Starting from [Web SDK 2.0.0-Beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/) you can create a custom Telemetry Processor that and filter specific requests based on any criteria you'd like, such as request endpoint URL or duration.

More details on [how to configure Telemetry Processors](https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-filtering-sampling/#filtering)

**Comment by SergeyKanzhelev** [comment]
Also if you want to ignore the current http request during request execution you can access it using this extension method for `HttpContext` https://github.com/Microsoft/ApplicationInsights-server-dotnet/blob/master/Src/Web/Web.Shared.Net/HttpContextExtension.cs#L17 and mark it with the custom property. You'd also need a telemetry processor that will filter this transaction out.
