### ISSUE TITLE
Web NuGet is removing a custom TelemetryProcessor if any are present.

### ISSUE THREAD

**Issue by tokaplan** [Microsoft/ApplicationInsights-server-dotnet#24]
Due to the second argument of XPath's **contains** expression not being quoted in Web NuGet transformation, it appears that XDT randomly removes the first TelemetryProcessor it encounters and the xdt:Locator filter is not being applied.

https://github.com/Microsoft/ApplicationInsights-server-dotnet/blob/aac44ef4cf526143d71683464e1c5a956cdeb5df/Src/Web/Web.Nuget/Resources/ApplicationInsights.config.install.xdt lines 50-52 currently in develop.

**Comment by abaranch** [comment]
Fixed in #25
