### ISSUE TITLE
Configuring two httpmodules generated two identical requests

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-server-dotnet#26]
HttpModule should use a singleton to generate Begin and End ETW events so we will not send duplicates when misconfigured

**Comment by abaranch** [comment]
We cannot reliably detect if you have identical modules defined in the config, or IIS creats several HttpApplication instances: http://erraticdev.blogspot.com/2011/01/how-to-correctly-use-ihttpmodule-to.html 
@SergeyKanzhelev Let's close this by design.

**Comment by SergeyKanzhelev** [comment]
As discussed offline we may want to try to detect dups inside a single request.
